import { chromium } from '../../web/node_modules/@playwright/test/index.mjs';
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const out = fileURLToPath(new URL('../../build/web-validation/',import.meta.url));
mkdirSync(out,{recursive:true});
const url=process.env.DEMO_URL??'http://127.0.0.1:4173/';
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
let page=await context.newPage();
const errors=[];page.on('pageerror',error=>errors.push(error.message));
const checks=[];
function check(name,pass,detail){checks.push({name,pass:Boolean(pass),detail});if(!pass)throw new Error(name+': '+JSON.stringify(detail));}
const inspect=()=>page.evaluate(()=>window.__demo.inspect());
await page.clock.install();
await page.goto(url+'?qa=1');
await page.waitForFunction(()=>window.__demo,{timeout:30000});
check('menu loads real C/Wasm', (await inspect()).snapshot.configVersion===2);
await page.locator('[data-overlay="action"]').click();
await page.clock.runFor(100);
check('start advances fixed ticks',(await inspect()).snapshot.tick>0,await inspect());
const attacks=[];
for(let pattern=0;pattern<4;pattern++){
  await page.keyboard.press('r');await page.clock.runFor(34);
  await page.keyboard.down(String(pattern+1));await page.clock.runFor(34);
  let state=await inspect();
  check(`pattern ${pattern} accepted`,state.snapshot.pattern===pattern&&state.snapshot.accepted===1,state.snapshot.accepted);
  check(`pattern ${pattern} published warning`,state.snapshot.warnings.length>0);
  check(`pattern ${pattern} does not spawn during windup`,state.snapshot.bossBullets===0);
  const acceptedEnergy=state.snapshot.energy;
  await page.clock.runFor(100);
  check(`pattern ${pattern} held key single edge`,(await inspect()).snapshot.accepted===1);
  await page.keyboard.up(String(pattern+1));
  await page.clock.runFor(1100);
  state=await inspect();
  check(`pattern ${pattern} emits real bullets`,state.snapshot.bossBullets>0,state.snapshot.bossBullets);
  attacks.push({pattern,warningCount:state.snapshot.warnings.length,bossBullets:state.snapshot.bossBullets,energyAfterAccept:acceptedEnergy});
  await page.screenshot({path:out+`pattern-${pattern}.png`});
}
await page.keyboard.press('r');await page.clock.runFor(34);
await page.locator('.demo-skill').nth(0).click();await page.clock.runFor(34);
const beforeBusy=await inspect();
await page.locator('.demo-skill').nth(1).click();await page.clock.runFor(34);
const busy=await inspect();
check('busy request refuses once, no second accepted attack',busy.snapshot.accepted===1&&busy.snapshot.rejected===1);
check('busy refusal does not charge energy',busy.snapshot.energy>=beforeBusy.snapshot.energy);
await page.keyboard.press('Escape');
const paused=(await inspect()).snapshot;
await page.clock.runFor(2000);
const afterPause=await inspect();
check('pause freezes tick and energy',afterPause.phase==='paused'&&afterPause.snapshot.tick===paused.tick&&afterPause.snapshot.energy===paused.energy);
await page.locator('[data-overlay="action"]').click();await page.clock.runFor(100);
check('resume does not catch up paused time',(await inspect()).snapshot.tick-paused.tick<=8);
await page.keyboard.press('r');await page.clock.runFor(34);
await page.keyboard.press('4');await page.clock.runFor(34);
await page.clock.runFor(6500);
let poor=await inspect();
if(poor.phase==='playing'){
  const previous=poor.snapshot;await page.keyboard.press('4');await page.clock.runFor(34);poor=await inspect();
  check('default shower fully regains its cost during attack',poor.snapshot.accepted===previous.accepted+1&&previous.energy>=60,{energy:previous.energy});
}
await page.keyboard.press('r');await page.clock.runFor(34);
await page.setViewportSize({width:900,height:800});
const bounds=await page.locator('canvas').boundingBox();
await page.mouse.move(bounds.x+720/960*bounds.width,bounds.y+600/720*bounds.height);
await page.clock.runFor(250);
let moved=await inspect();
check('scaled pointer moves toward logical target',moved.snapshot.actors[0].x>500,moved.snapshot.actors[0]);
await page.mouse.move(899,799);await page.clock.runFor(34);
const stopped=(await inspect()).snapshot.actors[0];await page.clock.runFor(250);
check('pointer leaving arena stops movement',Math.abs((await inspect()).snapshot.actors[0].x-stopped.x)<.001);
await page.keyboard.down('a');await page.clock.runFor(200);await page.keyboard.up('a');
check('keyboard fallback moves Boss',(await inspect()).snapshot.actors[0].x<stopped.x-20);
await page.evaluate(()=>window.dispatchEvent(new Event('blur')));const blurred=await inspect();
await page.clock.runFor(500);
check('focus loss visibly pauses',blurred.phase==='paused'&&(await inspect()).snapshot.tick===blurred.snapshot.tick);
await page.locator('[data-overlay="action"]').click();await page.clock.runFor(34);
await page.mouse.click(bounds.x+100,bounds.y+100,{button:'right'});
check('right click pauses',(await inspect()).phase==='paused');
await page.keyboard.press('r');await page.clock.runFor(34);
check('restart resets HP, counters and plan',(await inspect()).snapshot.actors[0].hp===6&&(await inspect()).snapshot.accepted===0);
await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));
const cached=await inspect();await page.clock.runFor(200);
check('persisted pagehide handler pauses and keeps core',cached.phase==='paused'&&(await inspect()).snapshot.tick===cached.snapshot.tick);
await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));
await page.locator('[data-overlay="action"]').click();await page.clock.runFor(100);
check('persisted pageshow handler resumes RAF after explicit continue',(await inspect()).snapshot.tick>cached.snapshot.tick);
await page.keyboard.press('r');await page.clock.runFor(34);
await page.clock.runFor(30000);
const over=await inspect();
check('real student fire reaches Boss defeat',over.phase==='over'&&over.snapshot.status===2&&over.snapshot.bossHits===6,over.snapshot);
await page.clock.runFor(1000);check('terminal tick freezes',(await inspect()).snapshot.tick===over.snapshot.tick);
await page.screenshot({path:out+'defeat.png'});
await page.setViewportSize({width:1440,height:1000});
// Clock installation affects its context. Use a new context for actual RAF measurements.
await page.close();
const timingContext=await browser.newContext({viewport:{width:1440,height:1000}});
page=await timingContext.newPage(); page.on('pageerror',error=>errors.push(error.message));
await page.goto(url+'?qa=1');await page.waitForFunction(()=>window.__demo);
await page.locator('[data-overlay="action"]').click();await page.keyboard.press('2');
await page.waitForTimeout(3000);await page.screenshot({path:out+'playing.png'});
const performance=await inspect();
await page.keyboard.press('Escape');
check('browser has no uncaught runtime errors',errors.length===0,errors);
const bench=await timingContext.newPage();await bench.goto(url+'bench.html');
await bench.waitForFunction(()=>window.__bench,{timeout:30000});
const stress=await bench.evaluate(()=>window.__bench);
check('800 bullet render fixture completed',stress.frames===300,stress);
const report={browser:await browser.version(),checks,attacks,errors,normalSamples:performance.samples,stress};
writeFileSync(out+'browser-results.json',JSON.stringify(report,null,2));
console.log(JSON.stringify({browser:report.browser,checks:checks.length,passed:checks.filter(c=>c.pass).length,attacks,stress},null,2));
await browser.close();
